"""empty message

Revision ID: 303c89f14402
Revises: 97382a30f05c
Create Date: 2023-10-12 20:17:18.880712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303c89f14402'
down_revision = '97382a30f05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_data_all',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('downtown', sa.String(length=64), nullable=True),
    sa.Column('introduce', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('orientation', sa.String(length=128), nullable=True),
    sa.Column('pattern', sa.String(length=128), nullable=True),
    sa.Column('rent', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_data_all')
    # ### end Alembic commands ###
