"""version_2.0.1

Revision ID: 97382a30f05c
Revises: 647dd3f5a79f
Create Date: 2023-09-17 18:34:29.053464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97382a30f05c'
down_revision = '647dd3f5a79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('downtown', sa.String(length=64), nullable=True),
    sa.Column('introduce', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('orientation', sa.String(length=128), nullable=True),
    sa.Column('pattern', sa.String(length=128), nullable=True),
    sa.Column('rent', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_data')
    # ### end Alembic commands ###
